baseURL = 'https://MyrenRajh.github.io/Website/'
languageCode = 'en-us'
title = 'Myren Rajh'
theme = "hello-friend-ng"
paginate= 10

[params]
    author = "Myren Rajh"
    homeSubtitle = "MEng Mechanical Engineer"

    description = "Personal website and information repository"
    keywords = "homepage"
    images = [""]

    dateform = "Jan 2, 2006"
    dateformShor = "Jan 2"
    dateformNum = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    disableReadOtherPosts = false
    enableSharingButtons = true
    enableGlobalLanguageMenu = true

    [[params.social]]
        icon = "github"
        name = "GitHub"
        url = "https://github.com/MyrenRajh"
    
    [[params.social]]
        icon = "linkedin"
        name = "LinkeiIn"
        url = "https://www.linkedin.com/in/myrenrajh/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
    [languages.en]
        title = "Myren Rajh"
        # copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
        
    [languages.en.params]
        subtitle  = "MEng Mechanical Engineer"
        readOtherPosts = "Read other posts"
        keywords = ""
    
        [languages.en.params.logo]
        logoText = "mechanical enginer"
        logoHomeLink = "/Website"

            # or
            #
            # path = "/img/your-example-logo.svg"
            # alt = "Your example logo alt text"

[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"




